package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * AgainPurchaseDetail generated by hbm2java
 */
public class AgainPurchaseDetail implements java.io.Serializable {

	private Integer againPurchaseDetailId;
	private Integer againPurchaseId;
	private Integer productId;
	private Integer purchaseAmount;

	public AgainPurchaseDetail() {
	}

	public AgainPurchaseDetail(Integer againPurchaseId, Integer productId, Integer purchaseAmount) {
		this.againPurchaseId = againPurchaseId;
		this.productId = productId;
		this.purchaseAmount = purchaseAmount;
	}

	public Integer getAgainPurchaseDetailId() {
		return this.againPurchaseDetailId;
	}

	public void setAgainPurchaseDetailId(Integer againPurchaseDetailId) {
		this.againPurchaseDetailId = againPurchaseDetailId;
	}

	public Integer getAgainPurchaseId() {
		return this.againPurchaseId;
	}

	public void setAgainPurchaseId(Integer againPurchaseId) {
		this.againPurchaseId = againPurchaseId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getPurchaseAmount() {
		return this.purchaseAmount;
	}

	public void setPurchaseAmount(Integer purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

}
