package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private Integer orderDetailId;
	private Integer orderId;
	private Integer productId;
	private Integer demand;

	public OrderDetail() {
	}

	public OrderDetail(Integer orderId, Integer productId, Integer demand) {
		this.orderId = orderId;
		this.productId = productId;
		this.demand = demand;
	}

	public Integer getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getDemand() {
		return this.demand;
	}

	public void setDemand(Integer demand) {
		this.demand = demand;
	}

}
