package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * OutDemandDetail generated by hbm2java
 */
public class OutDemandDetail implements java.io.Serializable {

	private Integer outDemandDetailId;
	private Integer outDemandId;
	private Integer productId;
	private Integer outDemandAmount;

	public OutDemandDetail() {
	}

	public OutDemandDetail(Integer outDemandId, Integer productId, Integer outDemandAmount) {
		this.outDemandId = outDemandId;
		this.productId = productId;
		this.outDemandAmount = outDemandAmount;
	}

	public Integer getOutDemandDetailId() {
		return this.outDemandDetailId;
	}

	public void setOutDemandDetailId(Integer outDemandDetailId) {
		this.outDemandDetailId = outDemandDetailId;
	}

	public Integer getOutDemandId() {
		return this.outDemandId;
	}

	public void setOutDemandId(Integer outDemandId) {
		this.outDemandId = outDemandId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getOutDemandAmount() {
		return this.outDemandAmount;
	}

	public void setOutDemandAmount(Integer outDemandAmount) {
		this.outDemandAmount = outDemandAmount;
	}

}
