package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * OutDemand generated by hbm2java
 */
public class OutDemand implements java.io.Serializable {

	private Integer outDemandId;
	private Integer orderId;
	private Integer userId;
	private Date addTime;
	private String state;

	public OutDemand() {
	}

	public OutDemand(Integer orderId, Integer userId, Date addTime, String state) {
		this.orderId = orderId;
		this.userId = userId;
		this.addTime = addTime;
		this.state = state;
	}

	public Integer getOutDemandId() {
		return this.outDemandId;
	}

	public void setOutDemandId(Integer outDemandId) {
		this.outDemandId = outDemandId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
