package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String productSize;
	private double salePrice;
	private int stock;
	private int safeStock;
	private int supplierId;
	private Double purchasePrice;

	public Product() {
	}

	public Product(String productName, String productSize, double salePrice, int stock, int safeStock, int supplierId) {
		this.productName = productName;
		this.productSize = productSize;
		this.salePrice = salePrice;
		this.stock = stock;
		this.safeStock = safeStock;
		this.supplierId = supplierId;
	}

	public Product(String productName, String productSize, double salePrice, int stock, int safeStock, int supplierId,
			Double purchasePrice) {
		this.productName = productName;
		this.productSize = productSize;
		this.salePrice = salePrice;
		this.stock = stock;
		this.safeStock = safeStock;
		this.supplierId = supplierId;
		this.purchasePrice = purchasePrice;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductSize() {
		return this.productSize;
	}

	public void setProductSize(String productSize) {
		this.productSize = productSize;
	}

	public double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(double salePrice) {
		this.salePrice = salePrice;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public int getSafeStock() {
		return this.safeStock;
	}

	public void setSafeStock(int safeStock) {
		this.safeStock = safeStock;
	}

	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	public Double getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(Double purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

}
