package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * PurchaseDetail generated by hbm2java
 */
public class PurchaseDetail implements java.io.Serializable {

	private Integer purchaseDetailId;
	private Integer purchaseId;
	private Integer productId;
	private Integer purchaseAmount;

	public PurchaseDetail() {
	}

	public PurchaseDetail(Integer purchaseId, Integer productId, Integer purchaseAmount) {
		this.purchaseId = purchaseId;
		this.productId = productId;
		this.purchaseAmount = purchaseAmount;
	}

	public Integer getPurchaseDetailId() {
		return this.purchaseDetailId;
	}

	public void setPurchaseDetailId(Integer purchaseDetailId) {
		this.purchaseDetailId = purchaseDetailId;
	}

	public Integer getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getPurchaseAmount() {
		return this.purchaseAmount;
	}

	public void setPurchaseAmount(Integer purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

}
