package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Receivable generated by hbm2java
 */
public class Receivable implements java.io.Serializable {

	private Integer receivableId;
	private Integer stockUpId;
	private Double totalAccount;
	private String payState;
	private Date addTime;

	public Receivable() {
	}

	public Receivable(Integer stockUpId, Double totalAccount, String payState, Date addTime) {
		this.stockUpId = stockUpId;
		this.totalAccount = totalAccount;
		this.payState = payState;
		this.addTime = addTime;
	}

	public Integer getReceivableId() {
		return this.receivableId;
	}

	public void setReceivableId(Integer receivableId) {
		this.receivableId = receivableId;
	}

	public Integer getStockUpId() {
		return this.stockUpId;
	}

	public void setStockUpId(Integer stockUpId) {
		this.stockUpId = stockUpId;
	}

	public Double getTotalAccount() {
		return this.totalAccount;
	}

	public void setTotalAccount(Double totalAccount) {
		this.totalAccount = totalAccount;
	}

	public String getPayState() {
		return this.payState;
	}

	public void setPayState(String payState) {
		this.payState = payState;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

}
