package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * SaleAccount generated by hbm2java
 */
public class SaleAccount implements java.io.Serializable {

	private Integer saleAccountlId;
	private Integer receivableId;
	private Date receiveDate;
	private Double totalAccount;

	public SaleAccount() {
	}

	public SaleAccount(Integer receivableId, Date receiveDate, Double totalAccount) {
		this.receivableId = receivableId;
		this.receiveDate = receiveDate;
		this.totalAccount = totalAccount;
	}

	public Integer getSaleAccountlId() {
		return this.saleAccountlId;
	}

	public void setSaleAccountlId(Integer saleAccountlId) {
		this.saleAccountlId = saleAccountlId;
	}

	public Integer getReceivableId() {
		return this.receivableId;
	}

	public void setReceivableId(Integer receivableId) {
		this.receivableId = receivableId;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public Double getTotalAccount() {
		return this.totalAccount;
	}

	public void setTotalAccount(Double totalAccount) {
		this.totalAccount = totalAccount;
	}

}
