package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * StockUpDetail generated by hbm2java
 */
public class StockUpDetail implements java.io.Serializable {

	private Integer stockUpDetailId;
	private Integer stockUpId;
	private Integer productId;
	private Integer stockUpAmount;

	public StockUpDetail() {
	}

	public StockUpDetail(Integer stockUpId, Integer productId, Integer stockUpAmount) {
		this.stockUpId = stockUpId;
		this.productId = productId;
		this.stockUpAmount = stockUpAmount;
	}

	public Integer getStockUpDetailId() {
		return this.stockUpDetailId;
	}

	public void setStockUpDetailId(Integer stockUpDetailId) {
		this.stockUpDetailId = stockUpDetailId;
	}

	public Integer getStockUpId() {
		return this.stockUpId;
	}

	public void setStockUpId(Integer stockUpId) {
		this.stockUpId = stockUpId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getStockUpAmount() {
		return this.stockUpAmount;
	}

	public void setStockUpAmount(Integer stockUpAmount) {
		this.stockUpAmount = stockUpAmount;
	}

}
