package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * StockUp generated by hbm2java
 */
public class StockUp implements java.io.Serializable {

	private Integer stockUpId;
	private Integer orderId;
	private Integer userId;
	private Date addTime;
	private String state;

	public StockUp() {
	}

	public StockUp(Integer orderId, Integer userId, Date addTime, String state) {
		this.orderId = orderId;
		this.userId = userId;
		this.addTime = addTime;
		this.state = state;
	}

	public Integer getStockUpId() {
		return this.stockUpId;
	}

	public void setStockUpId(Integer stockUpId) {
		this.stockUpId = stockUpId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
