package buaa.sem.amc.entity;
// Generated 2017-1-17 13:52:54 by Hibernate Tools 5.2.0.CR1

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private Integer supplierId;
	private String supplierCompany;
	private String linkMan;
	private String address;
	private String phone;
	private String email;
	private String productScope;

	public Supplier() {
	}

	public Supplier(String supplierCompany, String linkMan, String address, String phone) {
		this.supplierCompany = supplierCompany;
		this.linkMan = linkMan;
		this.address = address;
		this.phone = phone;
	}

	public Supplier(String supplierCompany, String linkMan, String address, String phone, String email,
			String productScope) {
		this.supplierCompany = supplierCompany;
		this.linkMan = linkMan;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.productScope = productScope;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierCompany() {
		return this.supplierCompany;
	}

	public void setSupplierCompany(String supplierCompany) {
		this.supplierCompany = supplierCompany;
	}

	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getProductScope() {
		return this.productScope;
	}

	public void setProductScope(String productScope) {
		this.productScope = productScope;
	}

}
